MATH_FUNC(SQRT, FRAC(NUM(1), MUL(2, SQRT(VAR))))

MATH_FUNC(LN, FRAC(NUM(1), VAR))

MATH_FUNC(SIN, COS(VAR))

MATH_FUNC(COS, NEG(SIN(VAR)))

MATH_FUNC(TAN, FRAC(NUM(1), POW(COS(VAR), 2)))

MATH_FUNC(COT, FRAC(NUM(-1), POW(SIN(VAR), 2)))

MATH_FUNC(ARCSIN,
            FRAC(NUM(1), SQRT(SUB(NUM(1), POW(VAR, 2)))))

MATH_FUNC(ARCCOS,
            FRAC(NUM(-1), SQRT(SUB(NUM(1), POW(VAR, 2)))))

MATH_FUNC(ARCTAN,
            FRAC(NUM(1), ADD(NUM(1), POW(VAR, 2))))

MATH_FUNC(ARCCOT,
            FRAC(NUM(-1), ADD(NUM(1), POW(VAR, 2))))
