MATH_FUNC(SQRT, FRAC(NUM(1), MUL(2, SQRT(RIGHT))))

MATH_FUNC(LN, FRAC(NUM(1), RIGHT))

MATH_FUNC(SIN, COS(RIGHT))

MATH_FUNC(COS, NEG(SIN(RIGHT)))

MATH_FUNC(TAN, FRAC(NUM(1), POW(COS(RIGHT), 2)))

MATH_FUNC(COT, FRAC(NUM(-1), POW(SIN(RIGHT), 2)))

MATH_FUNC(ARCSIN,
            FRAC(NUM(1), SQRT(SUB(NUM(1), POW(RIGHT, 2)))))

MATH_FUNC(ARCCOS,
            FRAC(NUM(-1), SQRT(SUB(NUM(1), POW(RIGHT, 2)))))

MATH_FUNC(ARCTAN,
            FRAC(NUM(1), ADD(NUM(1), POW(RIGHT, 2))))

MATH_FUNC(ARCCOT,
            FRAC(NUM(-1), ADD(NUM(1), POW(RIGHT, 2))))
